### ISSUE TITLE
Absorption visual bug

### ISSUE THREAD

**Issue by ghost** [WarzoneMC/Warzone#278] opened 2018-04-14 13:16 UTC
When eating a golden apple, if the map switches, any left over absorption you had at the end of the game gets carried over to the next game, but does not actually do anything.

*This issue was submitted through our issue submission tool.*

**Comment by tjhubz** [comment] 2018-04-14 14:10
Potential fix: Clear effects at the end of the game

**Comment by MatrixTunnel** [comment] 2018-04-14 18:09
This is a Minecraft visual bug. Effects are cleared when the match switches so I'm not sure this can be fixed

**Comment by tjhubz** [comment] 2018-04-14 19:06
I mean at the end of the match, there's no need to have effects on when the game ends.

**Comment by MatrixTunnel** [comment] 2018-04-14 19:14
After testing, the absorption hearts are cleared when the match cycles. Closing this report since I can't reproduce

**Comment by MatrixTunnel** [comment] 2018-04-14 19:29
Interesting... I just did more testing and cleared my effects before switching maps (hearts went away). After teleportation, the hearts were back (but only sometimes).

This is a visual bug that we can't do much about, unfortunately.
> Tested versions `1.8.9`, `1.12.2`

**Closed** 2018-10-04 22:49 UTC
Labels: bug
