### ISSUE TITLE
/mask (a quick and useful command for the staff team)

### ISSUE THREAD

**Issue by dependants** [WarzoneMC/Warzone#261] opened 2018-03-29 08:40 UTC
I'd like to suggest a new feature for staff members to support the ease of catching rule-breakers in the act.

From previous experience on a Minecraft server, there was a masking command. 
/mask - a command that lets you mask as a different rank.

For example; if you had the MOD tag, you would be able to select another rank. Such as VIP or the default player rank.

This would work with /nick, ([https://github.com/WarzoneMC/Warzone/issues/250](url))

**EXAMPLE**
SR.MOD BennyDoesStuff
(/mask)
VIP BennyDoesStuff
(/nick)
VIP Th0mas81

This command is extremely useful as you can hide your identity and seek rule-breakers without showing that you're currently online.

**Comment by jellz** [comment] 2018-03-29 09:08
Same comment as the /nick suggestion;
> Seems unnecessary imo, should just add a /vanish for staff

**Comment by scorpion808** [comment] 2018-03-29 15:40
^ and maybe silent join as well

**Comment by BennyDoesTheStuff** [comment] 2018-03-29 23:17
duplicate of #250

**Comment by MatrixTunnel** [comment] 2018-03-30 00:33
Not a dupe

**Comment by BennyDoesTheStuff** [comment] 2018-03-30 01:05
It very much so is a duplicate. The only difference is the command and the rank. I literally see no reason keeping this open.

**Comment by jellz** [comment] 2018-03-30 01:17
Not a duplicate.

**Comment by tjhubz** [comment] 2018-03-31 21:20
Essentially same effect as /nick, I agree with benny.

**Closed by tjhubz** 2018-03-31 21:20 UTC
