### ISSUE TITLE
Add /Vote /rate and /popular

### ISSUE THREAD

**Issue by Bearinx** [WarzoneMC/Warzone#196] opened 2017-11-10 22:19 UTC
The /vote command can be used like:
/vote map [map name] 
to vote for the next map to be played (Available for all users)

The /rate command can be used like:
/rate [map name] 1-5 
to rate a map on how much you enjoy the map (Available for all users)

The /popular command can be used like:
/popular 
this command will take the ratings of the maps add it up and score it then it will be put into a top 10 were people can type /popular and it will list those top 10 maps

**Comment by Bearinx** [comment] 2017-11-12 13:19
Maybe at the end of a match, 5 maps are broadcasted in chat for people to vote for next. This would make it so that people cant play maps in a loop. These 5 maps can be of all game modes. The /rate command can have a bonus if you vote for a map you get +1 Exp and a way to make it so people can't spam vote and level up really fast if you just make it so if you vote for a map that you have voted for already you don't get any Exp, and to make it so people cant vote for all the maps in one short amount of time and get a blast of exp is you make it so they have to wait an hour between votes.

**Comment by BennyDoesTheStuff** [comment] 2018-02-26 01:01
Duplicate of #197

**Closed by BennyDoesTheStuff** 2018-02-26 01:01 UTC
