### ISSUE TITLE
Team Switching

### ISSUE THREAD

**Issue by LewisP2018** [WarzoneMC/Warzone#268] opened 2018-04-03 22:24 UTC
It might make it easier if you disabled the /join command when in-game. It's very annoying when people are team switching so they can win, do it for fun, etc.

**Comment by scorpion808** [comment] 2018-04-03 23:04
You don't need to make a whole another issue. The developers look at the comments as well. Duplicate of #171

**Closed** 2018-04-03 23:05 UTC
