### ISSUE TITLE
“/skip” Command 

### ISSUE THREAD

**Issue by PSV7** [WarzoneMC/Warzone#390] opened 2018-11-24 17:07 UTC
If players do not like the current map, they can use the command “/skip” to vote for it to switch to the next map in the rotation. Depending on how many players are online, a certain amount of votes will skip the map. 

i.e. - There are 10 players online and the map is switched to Rooted, so if let’s say if 8 people (a little above the majority) do “/skip” then the map will be skipped and the next one in the rotation will be played. 

I’m not sure what fair fraction of the online players using the command would qualify as a map switch. Majority seems like too little, so probably a bit above that would work. 

Semantics of this could be figured out later, but it’s something that seems balanced when a map that most people online aren’t in favor of is played. Ty!

**Comment by BennyDoesTheStuff** [comment] 2018-11-24 19:46
Duplicate of #72

**Closed by BennyDoesTheStuff** 2018-11-24 19:46 UTC

**Comment by PSV7** [comment] 2018-11-24 21:00
Okay since there is already a “/skip” command then I’ll just call mine “/

**Comment by Draem** [comment] 2018-11-24 21:03
rekt

**Comment by PSV7** [comment] 2018-11-25 16:02
My idea is not even a duplicate because I added a majority voting system that could fairly get maps skipped so why is it still closed.
