### ISSUE TITLE
Warzone.network IP

### ISSUE THREAD

**Issue by pdxryanpdx** [WarzoneMC/Warzone#264] opened 2018-04-01 11:54 UTC
When you join with the warzone.network IP. it doesn't work sending you to the minehut lobby

**Comment by BennyDoesTheStuff** [comment] 2018-04-01 18:00
I'm going to close this issue as it's not a bug with TGM itself. Though I definitely will note this with the admins and look into a fix for this.

**Closed by BennyDoesTheStuff** 2018-04-01 18:00 UTC
