### ISSUE TITLE
The Void.

### ISSUE THREAD

**Issue by D7F** [WarzoneMC/Warzone#229] opened 2018-02-21 07:22 UTC
Make it so that when u fall into the void, at some point, something detects you and /kills you, so people wont have to wait like 5 seconds for the person to die in the void...
it could be an option, if u want to turn it off or on, command can be /void

**Comment by BennyDoesTheStuff** [comment] 2018-02-21 07:37
Duplicate of #94

**Closed** 2018-02-22 20:18 UTC
