### ISSUE TITLE
Clean chat.

### ISSUE THREAD

**Issue by D7F** [WarzoneMC/Warzone#230] opened 2018-02-21 07:25 UTC
This command is ONLY for staff, and is used when there is some very bad word, such as someone spamming the word (NIGGER PUSSY) <--- that actually did happen once. And then, one of the staff members can clean chat so the other people wont have to see it.

**Comment by tjhubz** [comment] 2018-02-21 15:18
There’s no need to say the actual explitive.

**Comment by jellz** [comment] 2018-02-23 06:33
lmao, agree with @tjhubz 

also, _expletive*_

**Comment by BennyDoesTheStuff** [comment] 2018-02-28 02:13
Duplicate of #124

**Closed by BennyDoesTheStuff** 2018-02-28 02:13 UTC
